import { handle } from "@hono/node-server/vercel";
// @ts-expect-error dist/boot.js is generated by the Vercel build command before this function is bundled.
import app from "../dist/boot.js";

export const config = {
  maxDuration: 60,
};

export default handle(app);
